[package]
name = "hcdl"
version = "0.1.0"
authors = ["David O'Rourke <david.orourke@gmail.com>"]
edition = "2018"
license = "Apache-2.0 or MIT"

[dependencies]
anyhow = "1.0"
bytes = "0.5"
clap = "2.33"
dirs = "2.0"
gpgrv = "0.2"
hex = "0.4"
indicatif = "0.14"
serde_json = "1.0"
sha2 = "0.8"
zip = "0.5"

[dependencies.reqwest]
version = "0.10"
default-features = false
features = [
    "json",
    "rustls-tls",
    "stream",
]

[dependencies.serde]
version = "1.0"
features = [
    "derive",
]

[dependencies.tokio]
version = "0.2"
features = [
    "macros",
]
