[package]
name = "hcdl"
description = "Easily download and update HashiCorp tools"
version = "0.12.0"
authors = ["David O'Rourke <david.orourke@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/phyber/hcdl"
repository = "https://github.com/phyber/hcdl"
categories = [
    "command-line-utilities",
]
keywords = [
    "cli",
    "hashicorp",
]
exclude = [
    ".gitignore",
    ".github",
]

[features]
default = [
    "embed_gpg_key",
    "shell_completion",
]

embed_gpg_key = []
shell_completion = []

[dependencies]
anyhow = "1.0"
bytes = "1.0"
chrono = "0.4"
crc32fast = "1.2"
dirs = "4.0"
gpgrv = "0.3"
hex = "0.4"
indicatif = "0.16"
serde_json = "1.0"
sha2 = "0.10"
tempfile = "3.1"

[dependencies.clap]
version = "2.33"
features = [
    "wrap_help",
]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = [
    "gzip",
    "json",
    "rustls-tls",
]

[dependencies.serde]
version = "1.0"
features = [
    "derive",
]

[dependencies.tokio]
version = "1.0"
features = [
    "macros",
    "rt-multi-thread",
]

# Force this due to flate2 forcing us to lower zip versions, this is due to
# restrictions on flate2 versions in the zip-rs Cargo.toml
[dependencies.zip]
version = "0.5"
default-features = false
features = [
    "deflate",
]

[dev-dependencies]
lazy_static = "1.4"
mockito = "0.30"
pretty_assertions = "1.0"
