[package]
name = "hcdl"
description = "Easily download and update HashiCorp tools"
version = "0.1.0"
authors = ["David O'Rourke <david.orourke@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/phyber/hcdl"
repository = "https://github.com/phyber/hcdl"
categories = [
    "command-line-utilities",
]
keywords = [
    "cli",
    "hashicorp",
]
exclude = [
    ".gitignore",
    ".github",
]

[dependencies]
anyhow = "1.0"
bytes = "0.5"
chrono = "0.4"
clap = "2.33"
dirs = "3.0"
gpgrv = "0.2"
hex = "0.4"
indicatif = "0.15"
serde_json = "1.0"
sha2 = "0.9"
tempfile = "3.1"
zip = "0.5"

[dependencies.reqwest]
version = "0.10"
default-features = false
features = [
    "gzip",
    "json",
    "rustls-tls",
]

[dependencies.serde]
version = "1.0"
features = [
    "derive",
]

[dependencies.tokio]
version = "0.2"
features = [
    "macros",
]

[dev-dependencies]
lazy_static = "1.4"
mockito = "0.26"
pretty_assertions = "0.6"
