---
name: 'Continuous Integration'
on:
  push:
    branches:
      - 'main'
jobs:
  test:
    name: 'Test Current Stable Rust Version'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 1
      - name: 'Target Cache'
        uses: 'actions/cache@v1'
        env:
          cache-name: 'target-cache'
        with:
          path: 'target'
          key: "${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}"
      - name: 'Install Toolchain'
        uses: 'actions-rs/toolchain@v1'
        with:
          profile: 'minimal'
          toolchain: 'stable'
          override: true
      - name: 'Run Default Feature Tests'
        uses: 'actions-rs/cargo@v1'
        with:
          command: 'test'
      - name: 'Run No Embedded GPG Key Feature Tests'
        uses: 'actions-rs/cargo@v1'
        with:
          command: 'test'
          args: '--no-default-features'
  msrv:
    name: 'Test Minimum Supported Rust Version'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 1
      - name: 'Target Cache'
        uses: 'actions/cache@v1'
        env:
          cache-name: 'target-cache'
        with:
          path: 'target'
          key: "${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}"
      - name: 'Install Toolchain'
        uses: 'actions-rs/toolchain@v1'
        with:
          profile: 'minimal'
          toolchain: '1.40.0'
          override: true
      - name: 'Run Default Feature Tests'
        uses: 'actions-rs/cargo@v1'
        with:
          command: 'test'
      - name: 'Run No Embedded GPG Key Feature Tests'
        uses: 'actions-rs/cargo@v1'
        with:
          command: 'test'
          args: '--no-default-features'
  mandoc:
    name: 'Lint Man Page'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Install mandoc'
        run: |
          sudo apt install mandoc
      - name: 'Lint Man Page'
        run: |
          mandoc -T lint man/hcdl.1
