---
name: 'Publish Release'
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    name: 'Cargo Publish'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 1
      - name: 'Install Toolchain'
        uses: 'actions-rs/toolchain@v1'
        with:
          profile: 'minimal'
          toolchain: 'stable'
          override: true
      - name: 'Run Cargo Publish'
        uses: 'actions-rs/cargo@v1'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          command: 'publish'
